CREATE DATABASE Books IF NOT EXISTS;

USE Books;

CREATE TABLE Information IF NOT EXISTS(
Entry_ID INT auto_increment,
Title VARCHAR(255) NOT NULL,
Author VARCHAR(255) NOT NULL,
Genre VARCHAR(255) NOT NULL,
Publication_Date DATE NOT NULL,
ISBN VARCHAR(17) NOT NULL,
PRIMARY KEY (Entry_ID)
)

